# Generated by Django 5.1.3 on 2025-01-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_produto_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
